config/routes.rb
TumatemateWeb::Application.routes.draw do

  resources :carts do
    member do
      post 'confirm'
    end
  end

  devise_for :admins

  get "manual_pages/party"

  get "manual_pages/conditions"

  get "manual_pages/warranty"

  get "manual_pages/preparation"

  get "manual_pages/maintenance"

	get "manual_pages/contacts"

  resources :product_tags

  resources :tags

  resources :producers

  resources :users

  resources :basket_items

  resources :order_items

  resources :orders

  get "products/admin_index"
  resources :products

  root :to => 'products#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/basket_item.rb
class BasketItem < ActiveRecord::Base
  
  belongs_to :product
  belongs_to :cart
  
  attr_accessible :cart_id, :product_id, :product, :cart, :price, :quantity
  
  def total_price
    quantity * price
  end
  
  def total_weight
    if product.weight.nil?
      0
    else
      quantity * product.weight
    end
  end
  
  def remove_one
    quantity -= 1
  end
  
  def add_one
    quantity -= 1
  end
  
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  
  # GET /basket_items
  # GET /basket_items.json
  def index
    @basket_items = BasketItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @basket_items }
    end
  end

  # GET /basket_items/1
  # GET /basket_items/1.json
  def show
    @basket_item = BasketItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @basket_item }
    end
  end

  # GET /basket_items/new
  # GET /basket_items/new.json
  def new
    @basket_item = BasketItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @basket_item }
    end
  end

  # GET /basket_items/1/edit
  def edit
    @basket_item = BasketItem.find(params[:id])
  end

  def create
    @cart = current_cart
    product = Product.find(params[:product_id])    
    @basket_item = @cart.add_product(product.id)    
    respond_to do |format|
      if @basket_item.save
        format.html { 
          redirect_to @basket_item.cart, :notice => 'Basket item was successfully created.' 
        }        
        format.json { 
          render :json => @basket_item, :status => :created, :location => @basket_item 
        }
      else
        format.html { 
          render :action => "new" 
        }
        format.json { 
          render :json => @basket_item.errors, :status => :unprocessable_entity 
        }
      end
    end
  end
      
  # PUT /basket_items/1
  # PUT /basket_items/1.json
  def update
    @basket_item = BasketItem.find(params[:id])

    respond_to do |format|
      if @basket_item.update_attributes(params[:basket_item])
        if @basket_item.quantity > 0
          notice = 'Basket item was successfully updated.'          
        else
          @basket_item.destroy
          notice = 'Basket item was removed.'            
        end
        format.html { 
          redirect_to cart_path(current_cart), :notice => notice  
        }
        format.js {
          render :layout => false
        }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @basket_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/1
  # DELETE /basket_items/1.json
  def destroy
    @basket_item = BasketItem.find(params[:id])
    @basket_item.destroy
    
    @cart = current_cart

    respond_to do |format|
      format.html { 
        redirect_to cart_path(current_cart), :notice => 'Basket item was removed.'  
      }
      format.js {
        render :layout => false
      }
      format.json { head :no_content }
    end
  end  
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/views/basket_items/_basket_item.html.erb
<tr class="cart-item">
	<td class="cart-item-image">
		<%= link_to product_path(basket_item.product_id) do %>
			<%= image_tag basket_item.product.image_large(:thumb) %>
		<% end %>
	</td>
	<td class="cart-item-name">
		<b><%= basket_item.product.name %></b>
		<p> 
			<i><%= basket_item.product.descriptionS %></i>
		</p>
	</td>
	<td class="cart-item-quantity">
		<%= form_for(basket_item) do |f| %>
		<%= f.number_field :quantity, :onchange => "this.form.submit();", :size => 4, :class => "quantity" %>		
		<% end %>		
	</td>
	<td class="cart-item-price"><%= number_to_price(basket_item.total_price) %></td>	
	<td><%= button_to 'Odstranit', basket_item_path(basket_item), :method => :delete, :remote => true %></td>	
</tr>

app/views/basket_items/_form.html.erb
<%= form_for(@basket_item) do |f| %>
  <% if @basket_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket_item.errors.count, "error") %> prohibited this basket_item from being saved:</h2>

      <ul>
      <% @basket_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basket_items/destroy.js.erb
$('#cart').html("<%=j render(@cart) %>")

app/views/basket_items/edit.html.erb
<h1>Editing basket_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket_item %> |
<%= link_to 'Back', basket_items_path %>

app/views/basket_items/index.html.erb
<h1>Listing basket_items</h1>

<table>
  <tr>
    <th>Cart id</th>
    <th>Productid</th>
    <th>Price</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @basket_items.each do |basket_item| %>
  <tr>
    <td><%= basket_item.cart_id %></td>
    <td><%= basket_item.product_id %></td>
    <td><%= basket_item.price %></td>
    <td><%= basket_item.quantity %></td>
    <td><%= link_to 'Show', basket_item %></td>
    <td><%= link_to 'Edit', edit_basket_item_path(basket_item) %></td>
    <td><%= link_to 'Destroy', basket_item, :method => :delete, :confirm => 'Are you sure?' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Basket item', new_basket_item_path %>

app/views/basket_items/new.html.erb
<h1>New basket_item</h1>

<%= render 'form' %>

<%= link_to 'Back', basket_items_path %>

app/views/basket_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cart Id:</b>
  <%= @basket_item.cart_id %>
</p>

<p>
  <b>Productid:</b>
  <%= @basket_item.product_id %>
</p>

<p>
  <b>Price:</b>
  <%= @basket_item.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @basket_item.quantity %>
</p>


<%= link_to 'Edit', edit_basket_item_path(@basket_item) %> |
<%= link_to 'Back', basket_items_path %>