config/routes.rb
TumatemateWeb::Application.routes.draw do

  resources :carts do
    member do
      post 'confirm'
    end
  end

  devise_for :admins

  get "manual_pages/party"

  get "manual_pages/conditions"

  get "manual_pages/warranty"

  get "manual_pages/preparation"

  get "manual_pages/maintenance"

	get "manual_pages/contacts"

  resources :product_tags

  resources :tags

  resources :producers

  resources :users

  resources :basket_items

  resources :order_items

  resources :orders

  get "products/admin_index"
  resources :products

  root :to => 'products#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
  has_many :basket_items, dependent: :destroy
  
  # puts product into cart
  def add_product(product_id)
    current_item = basket_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = basket_items.build(:product_id => product_id)
      current_item.quantity = 1
      current_item.price = Product.find(product_id).price
    end
    current_item
  end
  
  def total_price
    basket_items.to_a.sum {
      |item| item.total_price
    }    
  end
  
  def total_weight
    basket_items.to_a.sum {
      |item| item.total_weight
    }
  end
  
end

app/controllers/carts_controller.rb
# encoding: UTF-8
class CartsController < ApplicationController
  
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
      @user = User.new
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to products_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    
    session[:cart_id] = nil

    respond_to do |format|
      format.html { 
        redirect_to products_url,
        notice: 'Obsah košíku byl vysypán na zem. Zaměstnanci jej nyní uklízí.' 
      }
      format.json { 
        head :ok 
      }
    end    
  end
  
  # incoming user defined by email or address + cart.id => send mail to gimli
  def confirm
    @cart = Cart.find(params[:id])
    user = User.new(params[:user])
    @message = "\n"
    order = ""
    @cart.basket_items.each do |item|
      order = order + "#{item.product.name}\t\t #{item.quantity}ks\t#{item.quantity * item.price}Kč\n"
    end
    
    @message = @message + order
    
    if params[:delivery] == "poštou"
      # check address
      @message = @message + "Poštovné\t\t   \t100.0Kč\n"
      @message = @message + "Celkem\t\t\t   \t#{@cart.total_price+100}Kč\n\n"
      @message = @message + "Částku #{@cart.total_price+100} (včetně 100Kč za poštovné) odešli na:\n"
      @message = @message + "účet č. 1014681489/6100\nvariabilní symbol: #{params[:id]}\n\nZásilka ti poté bude odeslána na adresu:\n"
      address = user.name + " " + user.surname + "\n" + user.street + "\n" + user.zipCode + " " + user.city
      @message = @message + address
      @message = @message + "\n\nZboží pro Tebe bude rezervováno po dobu 7 dní."
    else
      # check email valid?
      if user.email == ""
        flash[:alert]="emailová adresa je chybně zadaná"
        redirect_to :action => 'show'
        return
      end
      @message = @message + "Celkem\t\t\t   \t#{@cart.total_price}Kč\n\n"
      
      @message = @message + "Díky za objednávku. Na uvedeném emailu (#{user.email}) Tě budeme kontaktovat."
    end
    
    @message = @message + "\n\nNejsme plátci DPH.\nV případě jakýchkoli nesrovnalostí nás neváhej kontaktovat na emailu info@tumatemate.cz.\n\nDěkujeme za objednávku."
    # control email
    mail = ActionMailer::Base.mail(:from => "tumatemate", :to => user.email, :subject => "[Maté]: objednávka #{params[:id]}".encode("UTF-8"), :body => @message.encode("UTF-8"))
    mail.deliver
    # checkout email
    checkout = "Košík číslo: #{@cart.id}\n\n"
    checkout = checkout + order + "\n"
    if !address.nil?
      checkout = checkout + address + "\n"
    end
    checkout = checkout + "email: " + user.email + "\n\n"
    checkout = checkout + params[:message] + "\n"
    
    checkoutMail = ActionMailer::Base.mail(:from => "tumatemate", :to => "gimli@matfyz.cz, uhlirt@seznam.cz", :subject => "[Maté]: objednávka #{params[:id]}".encode("UTF-8"), :body => checkout.encode("UTF-8"))
    checkoutMail.deliver
    
    session[:cart_id] = nil
  end
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table class="cart-content">
	<tr class="cart-header"><th></th><th></th><th class="cart-item-weight">množství</th><th class="cart-item-price" id="price">cena celkem</th><th></th></tr>
	<%= render(cart.basket_items) %>
	<tr class="cart-footer"><th></th>
		<th class="cart-item-price">celkem:</th><th class="cart-item-weight"><%= cart.total_weight/1000 %>kg</th>
		<th class="cart-item-price"><%= number_to_price(cart.total_price) %></th>
		<th>
			<%= button_to 'Vysypat košík', cart, :method => :delete, :confirm => 'Košík bude zcela prázdný ... ?' %>	
		</th>
	</tr>
</table>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/confirm.html.erb
<div class="one column"></div>
<div class="ten columns">
	<h3>Objednané zboží:</h3>
	<pre>
		<%= @message %>
	</pre>
</div>
<div class="one column"></div>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<h2>Obsah košíku:</h2>
<div id="cart">
	<%= render @cart %>
</div>
<%= form_for @user, :url => url_for(:controller => 'carts', :action => 'confirm', :id => @cart.id), :method => :post do |f| %>
<%= label_tag :email, "Email:" %> <%= f.text_field :email %>
<p>
<%= radio_button_tag :delivery, "personal", false, :onchange => 'showDelivery()', :class => 'delivery' %> <b>Osobní předání v Praze</b>
<div class="paragraph-indent" id="personal-delivery">
	Místo a čas předání s Tebou domluvíme emailem.<br />
	Doručení je zdarma.<br />
	Platba při předání.<br />
</div>
</p>
<p>
<%= radio_button_tag :delivery, "post", false, :onchange => 'showDelivery()' %> <b>Doručení Českou poštou</b>
<div class="paragraph-indent" id="post-delivery">
	Účtujeme navíc <b>100Kč</b> za poštovné a balné.<br />
	Platbu je třeba provést předem převodem. Detaily platby se Ti zobrazí po potvrzení objednávky.<br />
	Zásilku ti odešleme po zaúčtování platby.<br />
	Jméno: <%= f.text_field :name %><br />
	Příjmení: <%= f.text_field :surname %><br />
	Ulice a č.p.: <%= f.text_field :street %><br />
	Pošta (obec): <%= f.text_field :city %><br />
	PSČ: <%= f.text_field :zipCode %>
</div>
</p>
<p>
	<%= radio_button_tag :delivery, "party", false, :onchange => 'showDelivery()' %> <b>Vyzvednutí na maté párty</b>
	<div class="paragraph-indent" id="party-delivery">
		K vyzvednutí na maté párty
	</div>
</p>
<%= text_area_tag(:message, "Prostor pro další sdělení", size: "24x6") %>
<%= f.submit 'Objednat' %>
<% end %>
</div>