config/routes.rb
TumatemateWeb::Application.routes.draw do

  resources :carts do
    member do
      post 'confirm'
    end
  end

  devise_for :admins

  get "manual_pages/party"

  get "manual_pages/conditions"

  get "manual_pages/warranty"

  get "manual_pages/preparation"

  get "manual_pages/maintenance"

	get "manual_pages/contacts"

  resources :product_tags

  resources :tags

  resources :producers

  resources :users

  resources :basket_items

  resources :order_items

  resources :orders

  get "products/admin_index"
  resources :products

  root :to => 'products#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :timeoutable, :recoverable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/basket_item.rb
class BasketItem < ActiveRecord::Base
  
  belongs_to :product
  belongs_to :cart
  
  attr_accessible :cart_id, :product_id, :product, :cart, :price, :quantity
  
  def total_price
    quantity * price
  end
  
  def total_weight
    if product.weight.nil?
      0
    else
      quantity * product.weight
    end
  end
  
  def remove_one
    quantity -= 1
  end
  
  def add_one
    quantity -= 1
  end
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
  has_many :basket_items, dependent: :destroy
  
  # puts product into cart
  def add_product(product_id)
    current_item = basket_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = basket_items.build(:product_id => product_id)
      current_item.quantity = 1
      current_item.price = Product.find(product_id).price
    end
    current_item
  end
  
  def total_price
    basket_items.to_a.sum {
      |item| item.total_price
    }    
  end
  
  def total_weight
    basket_items.to_a.sum {
      |item| item.total_weight
    }
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :postage, :time, :userId
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :orderId, :price, :productId, :quantity
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  attr_accessible :country, :description, :name
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :basket_items
  before_destroy :ensure_not_referenced_by_any_basket_item

  attr_accessible :descriptionL, :descriptionS, :price, :stock, :weight, :name, :image_large, :image_medium, :image_small
  has_attached_file :image_large, :styles => { :medium => "400x400>", :thumb => "100x100>" }
  has_attached_file :image_medium, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :image_small, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  private
  # ensure that there are no basket items referencing this product
  def ensure_not_referenced_by_any_basket_item
    if basket_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  attr_accessible :productId, :tagId
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :description
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :city, :country, :email, :name, :phone, :street, :surname, :zipCode
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :authenticate_admin!, :except => [:show, :index]
  before_filter :fetch_menu
  
  def fetch_menu
    @mateList = Product.all    
  end
  
  # GET /products
  # GET /products.json
  def admin_index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end    
  end
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.where('stock > ?', 0)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end    
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_filter :authenticate_admin!
  
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, :notice => 'Tag was successfully created.' }
        format.json { render :json => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, :notice => 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper
  
  def number_to_price(number)
    return "#{number_with_precision(number, :precision => 0)}Kč";
  end
  
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/manual_pages_helper.rb
module ManualPagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/product_tags_helper.rb
module ProductTagsHelper
end

app/helpers/products_helper.rb
# encoding: UTF-8
module ProductsHelper  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html=>{:multipart=>true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_small %><br />
    <%= f.file_field :image_small %>
  </div>
  <div class="field">
    <%= f.label :image_medium %><br />
    <%= f.file_field :image_medium %>
  </div>
  <div class="field">
    <%= f.label :image_large %><br />
    <%= f.file_field :image_large %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :descriptionS %><br />
    <%= f.text_area :descriptionS %>
  </div>
  <div class="field">
    <%= f.label :descriptionL %><br />
    <%= f.text_area :descriptionL %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :stock %><br />
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/admin_index.html.erb
<div class="row">
<p id="notice"><%= notice %></p>
<h1>Seznam všeho zboží</h1>

<table class="product-list">
  <tr>
    <th colspan="3">obrázky</th>
    <th>název</th>
    <th>cena</th>
    <th>krátký popis</th>
    <th>dlouhý popis</th>
    <th>váha</th>
    <th>sklad</th>    
    <th></th>
    <th></th>
    <th></th>    
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= image_tag product.image_small.url(:thumb) %></td>
    <td><%= image_tag product.image_medium.url(:thumb) %></td>
    <td><%= image_tag product.image_large.url(:thumb) %></td>
    <td class="product-list-name"><%= product.name %></td>
    <td class="product-list-price"><%= product.price %></td>
    <td class="product-list-description-short"><%= product.descriptionS %></td>
    <td class="product-list-description-long"><%= truncate(product.descriptionL, :length => 100) %></td>
    <td><%= product.weight %></td>
    <td><%= product.stock %></td>   
    <td><%= link_to 'Zobrazit', product %></td>
    <td><%= link_to 'Upravit', edit_product_path(product) %></td>
    <td><%= link_to 'Smazat', product, :method => :delete, :confirm => 'Zboží bude zcela vymazáno a nebude jej možné obnovit ... ?' %></td>    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/edit.html.erb
<div class="row">
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="row">
    <p id="notice">
        <%= notice %>
    </p>    
    <div class="one column"></div>
    <div class="ten columns">
    	<h3>Naše nabídka</h3>
    	<table id="product-list">
    		<% i=0 %>    		
        	<% @products.each do |product| %>
        		<% if i % 3 == 0 %>
        			<tr>
        		<% end %>             	
            <td>
            	<%= link_to(product) do %>
                <div class="name">
                     <%= product.name %> (<%= number_to_human(product.weight) %>g)
                </div>
                <div class="description">
                    <%= product.descriptionS %>
                </div>
                <%= image_tag product.image_large.url(:medium), :size => "200x200" %>
                <div class="price">
                    <%= number_to_human(product.price) %>Kč
                </div>
            	<% end %>
            </td>            
            <% i=i+1 %>
            <% if i % 3 == 0 %>
        		</tr>
        	<% end %>                    
        <% end %>
        <% if i % 3 != 0 %>
        	</tr>
        <% end %>
        </table>
    </div>
    <div class="one column"></div>
</div>

app/views/products/new.html.erb
<div class="row">
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<div class="one columns"></div>
<div class="two columns">
    <div class="menu">
        <ul>
            <% @mateList.each do |item|%>
            <li>
                <%= link_to item.name, :action => item.id %>
            </li>
            <% end %>
        </ul>
    </div>

</div>

<div class="five columns">
    <div class="preview-content">
        <%= image_tag @product.image_large.url(:medium), :class => "image-large" %>

        <div class="product-header">
            <div class="product-name">
                <%= @product.name %> (<%= number_to_human(@product.weight) %>g)
                <br/>
            </div>
            <div class="descriptionS">
                <%= @product.descriptionS %>
            </div>
        </div>

        <div class="info">
            <div class="product-price">
                <%= number_to_human(@product.price) %>Kč
            </div>
            <%= button_to 'Přidat do košíku', basket_items_path(product_id: @product) %>
            <div class="stock">
                <b>Skladem:</b>
                <%= @product.stock %> ks
            </div>
        </div>
    </div>
</div>
<div class="two columns product-description">
    <%= @product.descriptionL.html_safe %>
</div>
<div class="two columns"></div>